# Configuración automática de datasources para Grafana
# Este archivo configura InfluxDB como fuente de datos

apiVersion: 1

datasources:
  - name: InfluxDB-Urgencias
    uid: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: urgencias
      defaultBucket: urgencias
      tlsSkipVerify: true
    secureJsonData:
      token: mi-token-secreto-urgencias-dt
    isDefault: true
    editable: true
